quote to double quote

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -43,10 +43,10 @@ api:test:
     - 'mvn $MAVEN_CLI_OPTS $UNIPROT_RESOURCES -P coverage -DfailIfNoTests=false install -s ${MAVEN_SETTINGS} 2>&1 | grep "\[\(INFO\|ERROR\|WARN\)\]"'
     - |
       if [ "${PIPESTATUS[0]}" != "0" ]; then
-        echo "Maven failed. Pipe status = ${PIPESTATUS[0]}"
+        echo "Maven failed. Pipe status = ${PIPESTATUS[0]}";
         false
       fi
-    - 'echo "Maven install successful'
+    - 'echo "Maven install successful"
     - 'mkdir -p ./jacoco-report'
     - 'cp $JACOCO_AGGREGATE_REPORT ./jacoco-report/'
     - 'rm -rfv ./*/target/*.jar'
