attempting fix

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -42,13 +42,12 @@ api:test:
   script:
     - 'mvn $MAVEN_CLI_OPTS $UNIPROT_RESOURCES -P coverage -DfailIfNoTests=false install -s ${MAVEN_SETTINGS} 2>&1 | grep "\[\(INFO\|ERROR\|WARN\)\]"'
     - |
-      if [ "${PIPESTATUS[1]}" != "0" ]; then
-        echo "mvn failed"
+      if [ "${PIPESTATUS[0]}" != "0" ]; then
+        echo "Maven failed. Pipe status = ${PIPESTATUS[0]}"
         false
       fi
     - 'mkdir -p ./jacoco-report'
     - 'cp $JACOCO_AGGREGATE_REPORT ./jacoco-report/'
-    - 'ls ./*/target/*.jar'
     - 'rm -rfv ./*/target/*.jar'
   artifacts:
     when: always
